name: 기상 감시 봇

on:
  schedule:
    - cron: '*/10 * * * *'  # 10분 간격
  workflow_dispatch:      # 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 기본 라이브러리 설치
        run: pip install requests

      - name: 봇 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      # ★★★ 여기가 수정된 핵심입니다! ★★★
      - name: 기록 저장 (JSON 데이터)
        run: |
          git config --global user.name "WeatherBot"
          git config --global user.email "bot@noreply.github.com"
          # 기존 txt 파일 대신 json 파일을 저장하도록 변경
          git add last_sent_data.json || true
          git commit -m "Update weather status data" || true
          git push
