name: 기상 감시 봇

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 기본 라이브러리 설치
        run: pip install requests

      - name: 봇 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: 기록 저장 (TXT 파일 업데이트)
        run: |
          git config --global user.name "WeatherBot"
          git config --global user.email "bot@noreply.github.com"
          
          # 1. 최신 코드 당겨오기
          git pull
          
          # 2. 기존 txt 파일 담기 (이미 있어서 100% 성공)
          git add last_sent.txt
          
          # 3. 변경사항 저장
          if ! git diff --cached --quiet; then
            git commit -m "Update weather status (txt) [skip ci]"
            git push
          else
            echo ">> 변경사항 없음"
          fi
