name: 기상 감시 봇

on:
  schedule:
    - cron: '*/10 * * * *'  # 10분 간격
  workflow_dispatch:      # 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 저장소에 파일 쓸 권한 (필수)

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 기본 라이브러리 설치
        run: pip install requests

      - name: 봇 실행
        env:
          # Secrets에 넣어둔 토큰을 꺼내서 파이썬에게 전달
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      # ★★★ 여기가 수정되었습니다! ★★★
      - name: 기록 저장 (JSON 데이터)
        run: |
          git config --global user.name "WeatherBot"
          git config --global user.email "bot@noreply.github.com"
          
          # [중요] 이제 txt가 아니라 json 파일을 저장합니다!
          git add last_sent_data.json || true
          
          git commit -m "Update weather status data" || true
          git push
