name: 기상 감시 봇

on:
  schedule:
    - cron: '*/10 * * * *'  # 10분마다 실행
  workflow_dispatch:      # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ★ 저장 권한 필수

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 기본 라이브러리 설치
        run: pip install requests

      - name: 봇 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: 기록 저장 (JSON 강제 저장)
        run: |
          # 1. 봇 신원 설정
          git config --global user.name "WeatherBot"
          git config --global user.email "bot@noreply.github.com"
          
          # 2. 최신 상태 동기화 (충돌 방지)
          git pull
          
          # 3. JSON 파일 강제 추가
          # (파일이 없어도 에러 안 나게 || true 처리 안 함. 무조건 있어야 함)
          git add last_sent_data.json
          
          # 4. 변경사항 확인 및 저장
          # "변경 사항이 있니?" 하고 물어봄
          if ! git diff --cached --quiet; then
            echo ">> 변경사항 발견! 저장합니다."
            git commit -m "Update weather data [skip ci]"
            git push
          else
            echo ">> 변경사항이 없습니다. 저장을 건너뜁니다."
          fi
